name: Publish to FTP on Push

on:
  workflow_dispatch:

  push:
    branches:
      - develop      

jobs:
  publish:
    runs-on: windows-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and publish
        run: |
          msbuild /p:Configuration=Release /p:OutputPath=./publish_output
          echo "::set-output name=publish_path::$(pwd)/publish_output"

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ steps.build.outputs.publish_path }}
          remote-dir: ${{ vars.FTP_REMOTE_DIR }}
