name: Testing Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop      

jobs:
  publish:
    runs-on: windows-2019
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Set NuGet Version
        run: echo "NUGET_VERSION=5.x" >> $GITHUB_ENV
             
      - name: Restore Packages
        run: nuget restore JBQ\JBQ.sln

      - name: Build Solution
        run: |
          msbuild.exe JBQ\JBQ.sln /p:Configuration=Release /p:OutputPath=./publish_output
          echo "::set-output name=publish_path::$(pwd)/publish_output"

      - name: Upload via FTP
        uses: dennisameling/ftp-upload-action@v1
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: ${{ steps.build.outputs.publish_path }}/
          server_dir: /${{ vars.FTP_REMOTE_DIR }}/ # Should always end with /    
          secure: false
