name: Testing Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: windows-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Restore NuGet packages
        run: nuget restore JBQ\JBQ\JBQ.csproj -PackagesDirectory packages

      - name: Build and publish
        run: |
          msbuild JBQ\JBQ\JBQ.csproj /p:Configuration=Release /p:OutputPath=./publish_output
          echo "::set-output name=publish_path::$(pwd)/publish_output"

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ steps.build.outputs.publish_path }}
          remote-dir: ${{ vars.FTP_REMOTE_DIR }}
