name: Testing Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - develop      

jobs:
  publish:
    runs-on: windows-2019
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Set NuGet Version
        run: echo "NUGET_VERSION=5.x" >> $GITHUB_ENV
       
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
  
      - name: Create Build Directory
        run: mkdir build
      
      - name: Restore Packages
        run: nuget restore JBQ\JBQ.sln

      - name: Build Solution
        run: |
          msbuild.exe JBQ\JBQ.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
          echo "::set-output name=publish_path::$(pwd)/build"

      - name: Upload via FTP
        uses: dennisameling/ftp-upload-action@v1
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: build/ # Should always end with /
          server_dir: ./${{ vars.FTP_REMOTE_DIR }}/ # Should always end with /    
          secure: false
